#!/bin/bash
##########################################################################
# AUTHOR:       Adam Piper (adam@ahri.net)
# DATE:         2009-12-17
# LICENSE:      GPL3
# LICENSE TEXT: http://www.gnu.org/licenses/gpl-3.0.html
##########################################################################

##########################################################################
# DESCRIPTION
##########################################################################
# Script to mount specified system directories into tmpfs -- hopefully
# providing a speed benefit to a Linux system
##########################################################################


##########################################################################
# ASSUMPTIONS
##########################################################################
#
# 1) No allowance is made for the situation where a directory you wish to
#    speedhack is not held on the root device -- bindings are made to the
#    root device only
#
# 2) Due to technical limitations hardlinks cannot be copied over multiple
#    devices, as such this functionality is missing
#
# 3) The code assumes that the mount type will be one of those whose mount
#    source always equals its mount type (e.g. tmpfs, ramfs)
#
# 4) Building upon assumption (3), it is assumed that the mount type will
#    grow dynamically as data is added
#
##########################################################################

##########################################################################
# NOTE
##########################################################################
# tmpfs = RAM/SWAP
# ramfs = RAM
##########################################################################

config_file="/etc/speedhack.conf"
action="$1"

##########################################################################
# Utility functions
##########################################################################

log()
{
        local level="$1"
        local str="$2"

        shift; shift

        printf "%s %s: $str\n" "$(date +%Y%m%d%H%M%S)" "$level" "$@"
}

info()
{
        local str="$1"

        shift

        log "INFO" "$str" "$@"
}

warning()
{
        local str="$1"

        shift

        log "WARNING" "$str" "$@"
}

error()
{
        local str="$1"

        shift

        log "ERROR" "$str" "$@"
        exit 1
}

config()
{
        system_dirs=()

        local config_file="$1"
        local all_cfg_vars=()
        local req_cfg_vars=()
        local defaults=()
        local key=
        local val=
        local var=
        local i=
        local found=
        local missing=0
        local default=

        shift
        # build up all_cfg_vars and reg_cfg_vars
        while [[ ! -z $1 ]]; do
                key="${1#@}"
                key="${key%%:*}"
                default="${1#*:}"

                [[ $1 = @* ]] && req_cfg_vars=("${req_cfg_vars[@]}" "$key")
                all_cfg_vars=("${all_cfg_vars[@]}" "$key")

                defaults=("${defaults[@]}" $default)
                shift
        done

        if [[ ! -r "$config_file" ]]; then
                error "readable config file '%s' is required to run this script" "$config_file"
        fi

        # set some variables from config data
        local IFS="="
        while read -r key val; do
                ([[ -z $key ]] || [[ $key = \#* ]]) && continue

                found=0
                for var in "${all_cfg_vars[@]}"; do
                        [[ $var = $key ]] && found=1
                done

                if [[ $found -eq 0 ]]; then
                        info "ignoring unrecognised config key '%s'" "$key"
                        continue
                fi

                if [[ -z $val ]]; then
                        info "config key '%s' has no value set, ignoring" "$key"
                        continue
                fi

                if [[ "$key" = "dir" ]]; then
                        #info "Found directory '%s' in config file" "$val"
                        # build the system_dirs array
                        system_dirs=("${system_dirs[@]}" "$val")
                else
                        #info "Setting '%s' to '%s' from config file" "$key" "$val"
                        # set other vars
                        [[ -z ${!key} ]] || warning "value for key '%s' previously set to '%s', re-setting to '%s'" "${!key}" "$val"
                        eval "$key=\"\$val\""
                fi
        done < "$config_file"

        for ((i=0; i <= "${#all_cfg_vars[@]}"; i++)); do
                key="${all_cfg_vars[i]}"
                default="${defaults[i]}"

                if [[   -z "${!key}"  ]] &&
                   [[ ! -z "$default" ]]; then
                        eval "$key=\"\$default\""
                fi
        done

        # test that all required variable are set
        for key in "${req_cfg_vars[@]}"; do
                if [[ -z ${!key} ]]; then
                        missing=1
                        warning "config variable '%s' is required to run this script" "$var"
                fi
        done

        [[ missing -eq 0 ]] || error "missing cfg options"
}

##########################################################################
# Action definitions
##########################################################################

a_real_root_mount()
{
        local real_root_mount="$1"

        echo "$real_root_mount"

        exit 0
}

a_memory_mounts()
{
        local memory_mounts="$1"

        echo "$memory_mounts"

        exit 0
}

a_mount_type()
{
        local mount_type="$1"

        echo "$mount_type"

        exit 0
}

a_log_file()
{
        local log_file="$1"

        echo "$log_file"

        exit 0
}

a_bind_root()
{
        local real_root_mount="$1"

        mkdir -p "$real_root_mount" 2> /dev/null
        a_bind_dir "/" "$real_root_mount"

        return 0
}

a_unbind_root()
{
        local real_root_mount="$1"

        a_unbind_dir "$real_root_mount"

        return 0
}

a_bind_dir()
{
        local source_dir="$1"
        local target_dir="$2"

        info "binding '%s' to '%s'" "$source_dir" "$target_dir"
        mount -o bind "$source_dir" "$target_dir" || error "mount failed"

        return 0
}

a_unbind_dir()
{
        local target_dir="$1"

        info "unbinding '%s'" "$target_dir"
        umount "$target_dir" || error "umount failed"

        return 0
}

a_mount_dir()
{
        local memory_mounts="$1"
        local mount_type="$2"
        local inmemory_dir="$3"

        # make the required directories
        mkdir -p "$memory_mounts" 2> /dev/null

        # make the mirror dir
        mkdir -p "$inmemory_dir" 2> /dev/null

        if [[ ! -d $inmemory_dir ]]; then
                warning "directory '%s' does not exist; ignoring" "$inmemory_dir"
                continue
        fi

        info "mounting mirror '%s' as type '%s'" "$inmemory_dir" "$mount_type"
        mount -t "$mount_type" "$mount_type" "$inmemory_dir" || error "mount failed"

        return 0
}

a_unmount_dir()
{
        local inmemory_dir="$1"

        info "unmounting mirror '%s'" "$inmemory_dir"
        umount "$inmemory_dir" || error "unmount failed"

        return 0
}

a_sync()
{
        local source_dir="$1"
        local target_dir="$2"
        local verbose="$3"

        if   [[ ! -d $source_dir ]]; then
                warning "directory '%s' does not exist; ignoring" "$source_dir"
                return 1

        elif [[ ! -d $target_dir ]]; then
                warning "directory '%s' does not exist; ignoring" "$target_dir"
                return 1
        fi

        info "syncing '%s' -> '%s'" "$source_dir/" "$target_dir/"

        if [[ $verbose = "Y" ]]; then
                verbose="v"
        else
                verbose=""
        fi

        rsync -ax$verbose --delete --force "$source_dir/" "$target_dir/" || error "rsync failed"

        return 0
}

##########################################################################
# Checks on dependency existence
##########################################################################

if ! which rsync 2>&1 > /dev/null; then
        error "rsync is required to run this script"
fi

if ! which speedhack 2>&1 > /dev/null; then
        error "speedhack is required to run this script"
fi

##########################################################################
# Program setup
##########################################################################

# set up required variables from config file
config "$config_file" @log_file:/var/log/speedhack.log @mount_type:tmpfs @real_root_mount:/mnt/real_root_mount @memory_mounts:/mnt/memory_mounts dir

# check that cfg specified directories exist
[[ -d `dirname "$log_file"` ]] || error "directory for log_file '%s' does not exist" "$log_file"

##########################################################################
# Business logic
##########################################################################

case "$action" in
        log_file)
                a_log_file "$log_file"
                ;;

        real_root_mount)
                a_real_root_mount "$real_root_mount"
                ;;

        memory_mounts)
                a_memory_mounts "$memory_mounts"
                ;;

        mount_type)
                a_mount_type "$mount_type"
                ;;

        bind_root)
                a_bind_root "$real_root_mount"
                ;;

        unbind_root)
                a_unbind_root "$real_root_mount"
                ;;

        mount_dirs|unmount_dirs|sync|sync_back|bind_dirs|unbind_dirs)
                # loop over dirs given in config and execute actions
                for system_dir in "${system_dirs[@]}"; do
                        if [[ $system_dir = @* ]]; then
                                ro=1
                        else
                                ro=0
                        fi

                        system_dir="${system_dir#@}"
                        physical_dir="$real_root_mount$system_dir"
                        inmemory_dir="$memory_mounts$system_dir"


                        if   [[ $action = "mount_dirs"   ]]; then
                                a_mount_dir "$memory_mounts" "$mount_type" "$inmemory_dir"

                        elif [[ $action = "unmount_dirs" ]]; then
                                a_unmount_dir "$inmemory_dir"

                        elif [[ $action = "sync"         ]]; then
                                a_sync "$physical_dir" "$inmemory_dir"

                        elif [[ $action = "sync_back"    ]] &&
                             [[ $ro -eq 0 ]]; then
                                a_sync "$inmemory_dir" "$physical_dir" "Y"

                        elif [[ $action = "bind_dirs"    ]]; then
                                a_bind_dir "$inmemory_dir" "$system_dir"

                        elif [[ $action = "unbind_dirs"  ]]; then
                                a_unbind_dir "$system_dir"
                        fi
                done
                ;;

        wind)
                speedhack "bind_root"  >> "$log_file" 2>&1 &&
                speedhack "mount_dirs" >> "$log_file" 2>&1 &&
                speedhack "sync"       >> "$log_file" 2>&1 &&
                speedhack "bind_dirs"  >> "$log_file" 2>&1

                err=$?

                exit $err
                ;;

        unwind)
                # It's expected that this process will fail in most cases,
                # since the system will most likely have processes running from
                # the mounts we've created. As such the strategy taken is to
                # save the data back as a priority and do the "cleaning up" as
                # possible.

                speedhack "sync_back"    >> "$log_file" 2>&1 &&
                speedhack "unbind_dirs"  >> "$log_file" 2>&1 &&
                speedhack "unmount_dirs" >> "$log_file" 2>&1 &&
                speedhack "unbind_root"  >> "$log_file" 2>&1

                exit $?
                ;;

        *)
                info "action must be one of:"
                info ""
                info "    log_file           -- print configured log_file"
                info "    real_root_mount    -- print configured real_root_mount"
                info "    memory_mounts      -- print configured memory_mounts"
                info "    mount_type         -- print configured mount_type"
                info ""
                info "    bind_root          -- bind the root to the specified real_root_mount"
                info "    mount_dirs         -- mount all in-memory dirs"
                info "    sync               -- copy system directories to their in-memory counterparts"
                info "    bind_dirs          -- bind system directories to their in-memory counterparts"
                info ""
                info "    unbind_dirs        -- remove system bindings"
                info "    sync_back          -- copy back any changes to read-write mounts"
                info "    unmount_dirs       -- unmount in-memory directories"
                info "    unbind_root        -- unbind system root"
                info ""
                info "    wind               -- perform bind_root, mount_dirs, sync, and bind_dirs"
                info "    unwind             -- perform sync_back, unbind_dirs, unmount_dirs, unbind_root"
                info ""
                error "unrecognised action '%s'" "$action"
                ;;
esac

exit 0
