#!/bin/sh
# Start/stop the speedhack daemon.
#
### BEGIN INIT INFO
# Provides:          speedhack
# Required-Start:    $remote_fs $syslog $time
# Required-Stop:     $remote_fs $syslog $time
# Default-Start:     2 3 4 5
# Default-Stop:      1
# Short-Description: Regular background program processing daemon
# Description:       Daemon to mount specified system directories into tmpfs and
#                    to mirror back the changes as they occur  -- hopefully
#                    providing a speed benefit to a Linux system
### END INIT INFO


SPEEDHACK="/usr/local/bin/speedhack"
test -x "$SPEEDHACK" || exit 0

PIDFILE=`speedhack pid_file`
# In some systems the pidfile might be (incorrectly) set to /etc
# if this pidfile is present, use it instead.
[ -r /etc/default/speedhack ] && . /etc/default/speedhack

. /lib/lsb/init-functions

# Read the system's locale and set speedhack's locale. This locale
# will be inherited by speedhack (used to set charset of emails)
# and tasks running under it.

parse_environment () 
{
    ENV_FILE="none"
    [ -r /etc/environment ] && ENV_FILE="/etc/environment"
    [ -r /etc/default/locale ] && ENV_FILE="/etc/default/locale"
    [ $ENV_FILE = none ] && return

    for var in LANG LC_ALL LC_CTYPE; do
        value=`grep -E "^[^#]*${var}=" $ENV_FILE | tail -n1 | cut -d= -f2`
        eval $var=$value
    done
}

# Parse the system's environment
if [ "$READ_ENV" = "yes" ] ; then
    export LANG LC_ALL LC_CTYPE
    parse_environment
fi


case "$1" in
start)	log_daemon_msg "Starting speedhack" "speedhack"
        "$SPEEDHACK" daemon
        log_end_msg $?
	;;
stop)	log_daemon_msg "Stopping speedhack" "speedhack"
        "$SPEEDHACK" kill_daemon
        log_end_msg $?
        ;;
restart) log_daemon_msg "Restarting (syncing back) speedhack" "speedhack" 
        "$SPEEDHACK" sync_back
        log_end_msg $?
        ;;
reload|force-reload) log_daemon_msg "Reloading speedhack (not supported)" "speedhack"
	# speedhack does not support reloading
        log_end_msg 1
        ;;
status) log_daemon_msg "Status check of speedhack (not supported)" "speedhack"
	# speedhack does not support status
        log_end_msg 1
	;;
*)	log_action_msg "Usage: /etc/init.d/speedhack {start|stop|restart}"
        exit 2
        ;;
esac
exit 0
